<?php

namespace App\Services\Zaakiy\Skills;

use App\Models\User;
use App\Services\Zaakiy\ZaakiySkill;
use App\Support\Branch\BranchContext;

class FaqSkill implements ZaakiySkill
{
    public function matches(string $message): bool
    {
        return preg_match('/faq|frequently asked|how do i|how can i|what is|help|user guide|manual|support|can i/i', $message) === 1;
    }

    public function run(string $message, User $user, BranchContext $branch): array
    {
        return [
            'skill' => 'faq',
            'data' => [
                'source' => 'Baithul Madeena business user guide',
                'instruction' => 'Answer the user using these verified product-help entries. If the question is about live branch data, direct the user to the relevant ERP screen or another authorized skill.',
                'records' => [
                    ['topic' => 'property_code', 'question' => 'How is a property code generated?', 'answer' => 'It uses branch, emirate, building, unit and property type inputs. Short codes are used where configured, spaces in the building name become hyphens, and the code is generated by the system.'],
                    ['topic' => 'tenant_agreement', 'question' => 'Why can a tenant agreement be rejected?', 'answer' => 'The property may be outside owner-agreement coverage, unavailable for the selected dates, assigned to another branch, or linked to an invalid tenant, property or owner agreement.'],
                    ['topic' => 'payments', 'question' => 'Which payment modes are supported?', 'answer' => 'Cash, cheque and bank transfer. Cheques require cheque details; bank transfers require a bank reference and transfer date.'],
                    ['topic' => 'receipts', 'question' => 'What happens when a payment line is paid?', 'answer' => 'The line becomes paid and a receipt link is available where supported. The receipt remains connected to the original financial transaction.'],
                    ['topic' => 'cheques', 'question' => 'What is the cheque lifecycle?', 'answer' => 'Received moves to Deposited and then Cleared. Deposited can become Bounced. Received or Deposited can be Cancelled. Invalid transitions are rejected.'],
                    ['topic' => 'voids', 'question' => 'Who can void a transaction?', 'answer' => 'A same-branch user with accounts.void permission. A reason is required and the original transaction history is preserved.'],
                    ['topic' => 'reports', 'question' => 'Which reports are available?', 'answer' => 'Owner Agreements, Tenant Agreements, Agreement Expiry, Tenant Outstanding, Owner Payable, Inward Receipts, Outward Vouchers, Daily Cash Movement, Petty Cash and Intelligent Report.'],
                    ['topic' => 'intelligent_report', 'question' => 'What is the Intelligent Report?', 'answer' => 'A management report combining backend-calculated cash, operational profitability, collections, occupancy, trends and deterministic leakage findings. It is not a statutory Profit and Loss statement.'],
                    ['topic' => 'zaakiy', 'question' => 'Can Zaakiy change ERP records?', 'answer' => 'No. Zaakiy is read-only. It can answer authorized questions and provide safe navigation links, but cannot post, void, edit or delete records.'],
                    ['topic' => 'branch_security', 'question' => 'Why cannot I see another branch record?', 'answer' => 'Branch isolation is enforced by the backend. Confirm the active branch and ask a Branch Admin or Super Admin if access is required.'],
                ],
            ],
            'navigation' => ['label' => 'Open Help & FAQ', 'url' => '/app/faq'],
        ];
    }
}
